-- 3세대
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (
    -- 2세대
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (
        -- 1세대
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    )
)
ORDER BY ID ASC;

