(
    SELECT PARENT.ID AS ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA PARENT JOIN ECOLI_DATA CHILD
    ON PARENT.ID = CHILD.PARENT_ID
    GROUP BY PARENT.ID
)
UNION
(
    SELECT ID, COUNT(*) - 1 AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE ID NOT IN (SELECT PARENT_ID AS ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
    GROUP BY ID
)
ORDER BY ID ASC;


