-- 오라클에서 없는 필드에 내용을 담아 출력하고 싶으면 우째???

SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, 
       PRODUCT_ID, 
       USER_ID, 
       SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') >= '2022-03-01' 
  AND TO_CHAR(SALES_DATE,'YYYY-MM-DD') <= '2022-03-31'
UNION ALL
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE, 
       PRODUCT_ID, 
       NULL AS USER_ID, 
       SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE,'YYYY-MM-DD') >= '2022-03-01' 
  AND TO_CHAR(SALES_DATE,'YYYY-MM-DD') <= '2022-03-31'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;