-- 자동차 종류가 세단 또는 SUV
-- 대여 가능 기간 : 20221101 ~ 20221130
-- 30일간의 대여 금액이 50만원 이상 200만원 미만

SELECT DISTINCT
    CC.CAR_ID, 
    CC.CAR_TYPE, 
    ROUND(CC.DAILY_FEE * 30 * ((100 - DP.DISCOUNT_RATE) * 0.01), 1) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH ON CC.CAR_ID = RH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
  AND RH.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= TO_DATE('20221101', 'YYYYMMDD')
  )
  AND DP.DURATION_TYPE = '30일 이상' 
  AND CC.DAILY_FEE * 30 * (100 - DP.DISCOUNT_RATE) * 0.01 BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;