-- ROUND, CEIL 머 이런거 쓰면 될 것 같은데 ㅜ
-- 리뷰평균점수는 소수점 세 번째 자리에서 반올림
-- 결과는 평균점수는 기준으로 내림차순 정렬
SELECT RI.REST_ID AS REST_ID,
       RI.REST_NAME AS REST_NAME, 
       RI.FOOD_TYPE AS FOOD_TYPE,
       RI.FAVORITES AS FAVORITES, 
       RI.ADDRESS AS ADDRESS,
       ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI JOIN REST_REVIEW RR 
    ON RI.REST_ID = RR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;