-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계
SELECT YEAR(OS.SALES_DATE) AS YEAR,
       MONTH(OS.SALES_DATE) AS MONTH,
       UI.GENDER AS GENDER,
       COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS
  ON UI.USER_ID = OS.USER_ID 
WHERE UI.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(OS.SALES_DATE, '%Y'), 
         DATE_FORMAT(OS.SALES_DATE, '%c'),
         UI.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;