-- 상품을 구매한 회원 수, 상품을 구매한 회원의 비율을 년, 월 별로 출력
WITH USER_TEMP AS (
    -- 2021년에 가입한 전체 회원들
    SELECT USER_ID
    FROM USER_INFO
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
)

SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
       EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
       COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_TEMP), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM USER_TEMP)
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;