-- ECOLI_TEMP : 각 세대별 대장균 ID, GENERATION 정보 담은 테이블
WITH RECURSIVE ECOLI_TEMP AS (
    SELECT ID AS ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT CHILD.ID AS ID, GENERATION + 1 AS GENERATION
    FROM ECOLI_TEMP PARENT JOIN ECOLI_DATA CHILD 
      ON PARENT.ID = CHILD.PARENT_ID
)
-- 세대별 자식 없는 대장균 구하기
SELECT COUNT(*) AS COUNT, ET.GENERATION AS GENERATION
FROM ECOLI_TEMP ET
WHERE NOT EXISTS(SELECT * FROM ECOLI_DATA WHERE PARENT_ID = ET.ID)
GROUP BY ET.GENERATION
ORDER BY ET.GENERATION ASC;