WITH RESULT AS (
    SELECT DISTINCT H.HISTORY_ID, 
           NVL(MAX(P.DISCOUNT_RATE), 0) AS DISCOUNT_RATE,
           C.DAILY_FEE, 
           END_DATE - START_DATE + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR C 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
      ON C.CAR_ID = H.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
      ON C.CAR_TYPE = P.CAR_TYPE
      AND (
          (H.END_DATE - H.START_DATE + 1 >= 90) AND P.DURATION_TYPE = '90일 이상'
          OR (H.END_DATE - H.START_DATE + 1 >= 30) AND P.DURATION_TYPE = '30일 이상'
          OR (H.END_DATE - H.START_DATE + 1 >= 7) AND P.DURATION_TYPE = '7일 이상'
      )
    WHERE C.CAR_TYPE = '트럭'
    GROUP BY H.HISTORY_ID, C.DAILY_FEE, (H.END_DATE - H.START_DATE + 1)
)
SELECT HISTORY_ID, 
       DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * DURATION AS FEE
FROM RESULT
ORDER BY FEE DESC, HISTORY_ID DESC;


