-- 같은 맛 아이스크림이라도 다른 출하 번호 가능
-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 상위 3개의 맛을 조회

SELECT TEMP.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS CNT
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION ALL
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS CNT
    FROM JULY
    GROUP BY FLAVOR
) AS TEMP
GROUP BY TEMP.FLAVOR
ORDER BY SUM(TEMP.CNT) DESC
LIMIT 3;