SELECT RESULT.FLAVOR
FROM (
    SELECT TEMP.FLAVOR, SUM(TEMP.TOTAL_ORDER) AS TOTAL
    FROM(
        SELECT FLAVOR, TOTAL_ORDER
        FROM JULY
        UNION 
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
    ) AS TEMP
    GROUP BY TEMP.FLAVOR
    ORDER BY TOTAL DESC 
    LIMIT 3
) RESULT;