# -- frontend 스킬을 가진 개발자 정보 조회

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE CODE = (
#     SELECT CODE
#     FROM SKILLCODES
#     WHERE CATEGORY = 'Front End'
# ) & SKILL_CODE != 0
# ORDER BY ID ASC;

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D JOIN SKILLCODES S
  ON S.CATEGORY = 'Front End'
WHERE D.SKILL_CODE & S.CODE != 0
ORDER BY D.ID ASC;
