-- 리뷰 가장 많이 작성한 회원의 리뷰들을 조회

SELECT A2.MEMBER_NAME, A1.REVIEW_TEXT, DATE_FORMAT(A1.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW A1 JOIN MEMBER_PROFILE A2 ON A1.MEMBER_ID = A2.MEMBER_ID
WHERE A1.MEMBER_ID = (
    SELECT MP.MEMBER_ID
    FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY MP.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY A1.REVIEW_DATE ASC, A1.REVIEW_TEXT ASC;