-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR
  ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM (
        SELECT MP.MEMBER_ID, COUNT(*) AS COUNT
        FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR
          ON MP.MEMBER_ID = RR.MEMBER_ID
        GROUP BY MP.MEMBER_ID
        ORDER BY COUNT DESC 
    )
    WHERE ROWNUM <= 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;