-- 부모가 있고  RARITY가 RARE
SELECT 
    II.ITEM_ID AS ITEM_ID,
    II.ITEM_NAME AS ITEM_NAME,
    II.RARITY AS RARITY
FROM ITEM_TREE IT JOIN ITEM_INFO II
ON It.ITEM_ID = II.ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NOT NULL AND EXISTS (
    SELECT * 
    FROM ITEM_INFO
    WHERE RARITY = 'RARE' AND ITEM_ID = IT.PARENT_ITEM_ID
)
ORDER BY II.ITEM_ID DESC;