-- PARENT_ID 가 갖는 GENOTYPE을 가지는지
SELECT ED.ID AS ID, ED.GENOTYPE AS GENOTYPE, PED.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED JOIN ECOLI_DATA PED
ON ED.PARENT_ID IS NOT NULL AND ED.PARENT_ID = PED.ID
WHERE ED.GENOTYPE & PED.GENOTYPE = PED.GENOTYPE
ORDER BY ED.ID ASC;
