-- 자동차 종류가 세단인 것 중 10월에 대여를 시작한 기록이 있는 자동차
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단'
  AND MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC